import Head from "next/head";
import React from "react";
import type { NextPageWithLayout } from "./_app";

const Error: NextPageWithLayout = () => {
  return (
    <div className="">
      <Head>
        <title>Error</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="">Error</div>
    </div>
  );
};

export default Error;
