import Head from "next/head";
import { ReactElement } from "react";
import { NextPageWithLayout } from "./_app";
import dynamic from "next/dynamic";
import Layout from "../components/Layout";
const HomePage = dynamic(() => import("../components/Home/HomePage"), {
  loading: () => <></>,
});

const Home: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>RankedDota</title>
        <meta name="theme-color" content="#fff" />
        <meta name="description" content="Generated by create next app" />
      </Head>
      <HomePage />
    </>
  );
};

Home.getLayout = function getLayout(page: ReactElement) {
  return <Layout>{page}</Layout>;
};

export default Home;
