import Head from "next/head";
import { ReactElement } from "react";
import HomePage from "../components/Home/HomePage";
import Layout from "../components/Layout";
import { NextPageWithLayout } from "./_app";
import { useEffect } from "react";
import { useAppSelector } from "../store";
import { fetchUserById } from "../store/Slices/globalDataSlice";
import { useAppDispatch } from "../store/hook";

const Home: NextPageWithLayout = () => {
  const dispatch = useAppDispatch();
  return (
    <>
      <Head>
        <title>RankedDota</title>
        <link rel="manifest" href="/manifest.json" />
        <link rel="icon" href="/darkLogo.png"></link>
        <meta name="theme-color" content="#fff" />
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="">
        <HomePage />
      </div>
    </>
  );
};

Home.getLayout = function getLayout(page: ReactElement) {
  return <Layout>{page}</Layout>;
};

export default Home;
