import React from "react";
import { ReactElement, useEffect } from "react";
import { GetStaticProps } from "next";
import Head from "next/head";
import { HeroesStatus } from "../../interfaces/heroes";
import stratsApiService from "../../services/stratsApi.service";
import HeroAllContainer from "../../components/Heroes/Overview/HeroAllContainer";
import Layout from "../../components/Layout";
import { NextPageWithLayout } from "../_app";
import { HeroesSubHeader, HeroHighWR } from "../../components/Heroes";
import { useAppDispatch } from "../../store/hook";
import {
  setHeaderImg,
  setSubHeaderMain,
} from "../../store/Slices/globalDataSlice";

type Props = {
  heroesStatus: HeroesStatus;
};

const HeroesPage: NextPageWithLayout<Props> = (props) => {
  const { heroesStatus } = props;
  const dispatch = useAppDispatch();
  useEffect(() => {
    dispatch(setSubHeaderMain(<HeroesSubHeader />));
    dispatch(setHeaderImg("/card1.jpg"));
  }, [dispatch]);
  return (
    <>
      <Head>
        <title>Heroes</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <section className="container m-auto">
        <HeroHighWR heroesStatus={heroesStatus} />
        <div className="mt-5">
          <HeroAllContainer heroesStatus={heroesStatus} />
        </div>
      </section>
    </>
  );
};

HeroesPage.getLayout = function getLayout(page: ReactElement) {
  return <Layout>{page}</Layout>;
};

export const getStaticProps: GetStaticProps = async () => {
  const res = await stratsApiService.getHeroStats();
  const heroesStatus: HeroesStatus = res.data.data.heroStats;
  return {
    props: {
      heroesStatus,
    },
  };
};

export default HeroesPage;
