import React from "react";
import { ReactElement } from "react";
import { GetServerSideProps, GetStaticProps } from "next";
import Head from "next/head";
import _ from "lodash";
import { HeroesStatus } from "../../interfaces/heroes";
import stratsApiService from "../../services/stratsApi.service";
import HeroAllContainer from "../../components/Heroes/Overview/HeroAllContainer";
import Layout from "../../components/Layout";
import { NextPageWithLayout } from "../_app";
import MyImage from "../../components/MyImage";
import { HeroesSubHeader, HeroHighWR } from "../../components/Heroes";

type Props = {
  heroesStatus: HeroesStatus;
};

const HeroesPage: NextPageWithLayout<Props> = (props) => {
  const { heroesStatus } = props;
  return (
    <>
      <Head>
        <title>Heroes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="container m-auto">
        <HeroHighWR heroesStatus={heroesStatus} />
        <div className="mt-5">
          <HeroAllContainer heroesStatus={heroesStatus} />
        </div>
      </section>
    </>
  );
};

HeroesPage.getLayout = function getLayout(page: ReactElement) {
  return <Layout subHeader={<HeroesSubHeader />}>{page}</Layout>;
};

export const getStaticProps: GetStaticProps = async () => {
  const res = await stratsApiService.getHeroStats();
  const heroesStatus: HeroesStatus = res.data.data.heroStats;
  return {
    props: {
      heroesStatus,
    },
  };
};

export default HeroesPage;
