import { GetServerSideProps } from "next";
import Head from "next/head";
import React, { ReactElement, useEffect } from "react";
import Layout from "../../components/Layout";
import { GameMode, Rank, Region } from "../../components/Matches";
import { Match } from "../../interfaces/matches";
import stratsApiService from "../../services/stratsApi.service";
import { NextPageWithLayout } from "../_app";

type Props = {
  gameMode: {
    ALL_PICK: Match[];
    CAPTAINS_MODE: Match[];
    ALL_PICK_RANKED: Match[];
    TURBO: Match[];
  };
  region: {
    CHINA: Match[];
    SEA: Match[];
    NORTH_AMERICA: Match[];
    SOUTH_AMERICA: Match[];
    EUROPE: Match[];
  };
  rank: {
    HERALD: Match[];
    GUARDIAN: Match[];
    CRUSADER: Match[];
    ARCHON: Match[];
    LEGEND: Match[];
    ANCIENT: Match[];
    DIVINE: Match[];
    IMMORTAL: Match[];
  };
};

const GraphsPage: NextPageWithLayout<Props> = (props) => {
  const { gameMode, region, rank } = props;
  return (
    <>
      <Head>
        <title>{`Matches > Graphs`} </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="container m-auto">
        <div className="my-10">
          <GameMode gameMode={gameMode} />
        </div>
        <div className="my-10">
          <Region region={region} />
        </div>
        <div className="my-10">
          <Rank rank={rank} />
        </div>
      </section>
    </>
  );
};

GraphsPage.getLayout = function getLayout(page: ReactElement) {
  return <Layout>{page}</Layout>;
};

export const getServerSideProps: GetServerSideProps<Props> = async () => {
  const res = await stratsApiService.getMatchesGraphsGameMode();
  const res1 = await stratsApiService.getMatchesGraphsRegion();
  const res2 = await stratsApiService.getMatchesGraphsRank();
  const {
    heroStats: { ALL_PICK, CAPTAINS_MODE, ALL_PICK_RANKED, TURBO },
  } = res.data.data;
  const {
    heroStats: { CHINA, SEA, NORTH_AMERICA, SOUTH_AMERICA, EUROPE },
  } = res1.data.data;
  const {
    heroStats: {
      HERALD,
      GUARDIAN,
      CRUSADER,
      ARCHON,
      LEGEND,
      ANCIENT,
      DIVINE,
      IMMORTAL,
    },
  } = res2.data.data;
  return {
    props: {
      gameMode: {
        ALL_PICK,
        CAPTAINS_MODE,
        ALL_PICK_RANKED,
        TURBO,
      },
      region: { CHINA, SEA, NORTH_AMERICA, SOUTH_AMERICA, EUROPE },
      rank: {
        HERALD,
        GUARDIAN,
        CRUSADER,
        ARCHON,
        LEGEND,
        ANCIENT,
        DIVINE,
        IMMORTAL,
      },
    },
  };
};

export default GraphsPage;
